#!/bin/bash

options=(
	style=round
	width=4.0
	hidpi=off
	active_color="gradient(top_left=0xfff5edf5,bottom_right=0xffd05db7)"
	inactive_color="gradient(top_left=0x88bdbdbd,bottom_right=0x88cba5e6)"
)

borders "${options[@]}"
