#!/bin/bash

options=(
	style=round
	width=4.0
	hidpi=off
	active_color="gradient(top_left=0xfffabd2f,bottom_right=0xffd65d0e)"
	inactive_color="gradient(top_left=0x88928374,bottom_right=0x883c3836)"
)

borders "${options[@]}"
