# 'titlebar-only' hides decorations but keeps macOS corner rounding
hide_window_decorations titlebar-only
window_padding_width 10

# Blend the titlebar area with the window background
macos_titlebar_color background

# --- Appearance ---
background_opacity 0.5

font_size 20.0

# BEGIN_KITTY_THEME
# Tokyo Night Moon
include current-theme.conf
# END_KITTY_THEME

# BEGIN_KITTY_FONTS
font_family      family="CaskaydiaCove Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS