# 'titlebar-only' hides decorations but keeps macOS corner rounding
hide_window_decorations titlebar-only
window_padding_width 10

# Blend the titlebar area with the window background
macos_titlebar_color background

# --- Appearance ---
background_opacity 0.95
background_blur 1

# --- Cursor ---
cursor_shape block
cursor_blink_interval 0
cursor_stop_blinking_after 0
shell_integration no-cursor

# Theme
include current-theme.conf

# Font
font_size 15.0
font_family      family="CaskaydiaCove Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto

# Border
window_border_width     3pt
active_border_color     #738b8b

progress_bar top
